# Generated by Django 5.0.2 on 2024-02-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('populacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_disputa', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CA', 'CAMPEONATO'), ('COPA', 'COPA')], default='CA', max_length=50)),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('regiao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('continente', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escudo', models.ImageField(null=True, upload_to='clubes')),
                ('nome', models.CharField(max_length=100)),
                ('ano_fundacao', models.PositiveIntegerField(default=1900)),
                ('divisao_atual', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('', ''), ('M', 'MASCULINO'), ('F', 'FEMININO')], default='', max_length=50)),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cidade')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.estado')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pais')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estado'),
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='jogadores')),
                ('posicao_principal', models.CharField(max_length=50)),
                ('numero_camisa', models.IntegerField()),
                ('sexo', models.CharField(choices=[('', ''), ('M', 'MASCULINO'), ('F', 'FEMININO')], default='', max_length=50)),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cidade')),
                ('clube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sem_clube', to='home.clube')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.estado')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pais')),
            ],
            options={
                'verbose_name': 'Jagador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pais'),
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('ano_conquista', models.PositiveIntegerField(default=1900)),
                ('data_exata', models.DateField()),
                ('clube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.clube')),
                ('competicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.competicao')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
            },
        ),
    ]
